### ISSUE TITLE
Windows Cannot find "bin\javaw"

### ISSUE THREAD

**Issue by The-Furious-Man** [Vislike/beat-saber-custom-song-repair-tool#1]
When I try to run the "Launch Repair Tool.bat" I get the above error

**Comment by IvanMazzoli** [comment]
Install Java and try again

https://www.java.com/it/download/manual.jsp

**Comment by Vislike** [comment]
Make sure you download the entire release zip file:
https://github.com/Vislike/beat-saber-custom-song-repair-tool/releases/download/v1.0/beat-saber-custom-song-repair-tool-1.0-bin-win.zip

And unzip it before trying to run "Launch Repair Tool.bat". The zip file has java bundled, so you don't have to install it.
